/* 
 * Trakerr API
 *
 * Get your application events and errors to Trakerr via the *Trakerr API*.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package trakerr

type AppEvent struct {

	// API key generated for the application
	ApiKey string `json:"apiKey,omitempty"`

	// (optional) Logging level, one of 'debug','info','warning','error', 'fatal', defaults to 'error'
	LogLevel string `json:"logLevel,omitempty"`

	// (optional) one of 'issue' or a custom string for non-issues, defaults to 'issue'
	Classification string `json:"classification,omitempty"`

	// type of the event or error (eg. NullPointerException)
	EventType string `json:"eventType,omitempty"`

	// message containing details of the event or error
	EventMessage string `json:"eventMessage,omitempty"`

	// (optional) event time in ms since epoch
	EventTime int64 `json:"eventTime,omitempty"`

	EventStacktrace []InnerStackTrace `json:"eventStacktrace,omitempty"`

	// (optional) event user identifying a user
	EventUser string `json:"eventUser,omitempty"`

	// (optional) session identification
	EventSession string `json:"eventSession,omitempty"`

	// (optional) application version information
	ContextAppVersion string `json:"contextAppVersion,omitempty"`

	// (optional) deployment stage, one of 'development','staging','production' or a custom string
	DeploymentStage string `json:"deploymentStage,omitempty"`

	// (optional) environment name (like 'cpython' or 'ironpython' etc.)
	ContextEnvName string `json:"contextEnvName,omitempty"`

	// (optional) language (like 'python' or 'c#' etc.)
	ContextEnvLanguage string `json:"contextEnvLanguage,omitempty"`

	// (optional) version of environment
	ContextEnvVersion string `json:"contextEnvVersion,omitempty"`

	// (optional) hostname or ID of environment
	ContextEnvHostname string `json:"contextEnvHostname,omitempty"`

	// (optional) browser name if running in a browser (eg. Chrome)
	ContextAppBrowser string `json:"contextAppBrowser,omitempty"`

	// (optional) browser version if running in a browser
	ContextAppBrowserVersion string `json:"contextAppBrowserVersion,omitempty"`

	// (optional) OS the application is running on
	ContextAppOS string `json:"contextAppOS,omitempty"`

	// (optional) OS version the application is running on
	ContextAppOSVersion string `json:"contextAppOSVersion,omitempty"`

	// (optional) Data center the application is running on or connected to
	ContextDataCenter string `json:"contextDataCenter,omitempty"`

	// (optional) Data center region
	ContextDataCenterRegion string `json:"contextDataCenterRegion,omitempty"`

	ContextTags []string `json:"contextTags,omitempty"`

	// (optional) The full URL when running in a browser when the event was generated.
	ContextURL string `json:"contextURL,omitempty"`

	// (optional) duration that this event took to occur in millis. Example - database call time in millis.
	ContextOperationTimeMillis int64 `json:"contextOperationTimeMillis,omitempty"`

	// (optional) CPU utilization as a percent when event occured
	ContextCpuPercentage int32 `json:"contextCpuPercentage,omitempty"`

	// (optional) Memory utilization as a percent when event occured
	ContextMemoryPercentage int32 `json:"contextMemoryPercentage,omitempty"`

	// (optional) Cross application correlation ID
	ContextCrossAppCorrelationId string `json:"contextCrossAppCorrelationId,omitempty"`

	// (optional) Device information
	ContextDevice string `json:"contextDevice,omitempty"`

	// (optional) Application SKU
	ContextAppSku string `json:"contextAppSku,omitempty"`

	CustomProperties CustomData `json:"customProperties,omitempty"`

	CustomSegments CustomData `json:"customSegments,omitempty"`
}
