/* 
 * Trakerr API
 *
 * Get your application events and errors to Trakerr via the *Trakerr API*.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package trakerr

type CustomDoubleData struct {

	CustomData1 float64 `json:"customData1,omitempty"`

	CustomData2 float64 `json:"customData2,omitempty"`

	CustomData3 float64 `json:"customData3,omitempty"`

	CustomData4 float64 `json:"customData4,omitempty"`

	CustomData5 float64 `json:"customData5,omitempty"`

	CustomData6 float64 `json:"customData6,omitempty"`

	CustomData7 float64 `json:"customData7,omitempty"`

	CustomData8 float64 `json:"customData8,omitempty"`

	CustomData9 float64 `json:"customData9,omitempty"`

	CustomData10 float64 `json:"customData10,omitempty"`
}
